S = start-comment stars <many-comments> stars end-comment
start-comment = '('
end-comment = ')'
<stars> = <'*'> +
<many-comments> = <inside-comment-1> +
whitespace = #'\s+'
word = #'[a-zA-Z]+'
number = #'[0-9]+'
punctuation-1 = #'[.,\/#!$%\^&\*;:{}=\-_`~()\']+'
<inside-comment-1> = '\n' | '\r\n' | '\r' | whitespace | word | number | punctuation-1