S = start-comment stars <many-comments> stars end-comment
start-comment = '('
end-comment = ')'
<stars> = <'*'> +
<many-comments> = <inside-comment-1> +
<inside-comment-1> = '\n' | '\r\n' | '\r'
<inside-comment-2> = '\r?\n'