S = one-comment <newline> version-assign <newline> <newline> controller
<controller> = "CONTROLLER" whitespace word whitespace <enclosure> <newline> whitespace data-type <newline> "END_CONTROLLER" <newline> *
data-type = "DATATYPE" whitespace word whitespace enclosure <newline> whitespace data-fill <newline> whitespace "END_DATATYPE"
data-fill = raw-type whitespace variable whitespace ? enclosure ? ending-op
enclosure = '(' any-assigns ')'
<version-assign> = variable <whitespace> assign-op <whitespace> float ending-op
any-assigns = any-assign-comma * any-assign 
any-assign = variable <whitespace> assign-op <whitespace> rhs-of-assignment
any-assign-comma = any-assign ',' newline whitespace
rhs-of-assignment = integer | float | string | version | base-number | "No" | "NoFamily"
assign-op = ':='
ending-op = ';'
one-comment = <start-comment> stars <inside-comment> stars <end-comment>
start-comment = <'('>
end-comment = <')'>
<stars> = <'*'> +
<inside-comment> = <allowed-inside-comment> +
<whitespace> = <#'\s+'>
variable = #'[a-zA-Z_]+[0-9]*' array-dimension ?
array-dimension = <'['> integer <']'>
word = #'[.\\0-9a-zA-Z_-]+'
one-or-more-words = (word whitespace) * word
string = quote one-or-more-words quote
quote = '\"'
integer = #'[0-9]+'
float = #'[-+]?[0-9]*\.[0-9]+'
version = "V" float
punctuation-1 = #'[.,\/#!$%\^&\*;:{}=\-_`~()\']+'
newline-simple = '\n' | '\r\n'
newline = <'\r' ? '\n'>
<allowed-inside-comment> = newline | whitespace | word | integer | punctuation-1
base-number = integer '#' word
raw-type = "DINT" | "REAL"