S = "        " tag
anything-word = #'[\'<>(),$=\:.\\0-9a-zA-Z_-]+'
one-or-more-anythings = (anything-word whitespace) * anything-word ? whitespace ?
anything-string = quote one-or-more-anythings quote
quote = '\"'
ending-op = ';'
assign-op = ':='
array-dimension = <'['> integer <']'>
array-comment = "COMMENT[" integer ']'
dot-comment = "COMMENT" ('.' variable) * ('.' integer) ?
tag-comment-assign = (array-comment | dot-comment) whitespace assign-op whitespace anything-string
tag-radix-assign = "RADIX" whitespace assign-op whitespace radix-type
tag-description-assign = "Description" whitespace assign-op whitespace anything-string
tag-enclosure-assign = tag-radix-assign | tag-description-assign | tag-comment-assign
tag-enclosure = '(' (tag-enclosure-assign ',' newline whitespace) * tag-enclosure-assign ')'
newline = <'\r' ? '\n'>
raw-type = "DINT" | "REAL" | "SINT" | "BOOL" | "INT" | "STRING"
array-dimmed-raw-type = raw-type array-dimension ?
native-type = raw-type | "BIT"
custom-type = "SockAddr" | "STR_OUT" | "STR_4096" | "Gas_Alm" | "Gas_Stat" | "MBTransaction" | "STR_1" | "Always"
 | "HMI_R_Gas" | "HMI_R_PLC" | "HMI_W" | "Local_Chassis" | "OpenConnParams"
radix-type = "Float" | "Decimal"
array-dimmed-type = (raw-type | custom-type) array-dimension ?
<whitespace> = <#'\s+'>
variable = #'[0-9a-zA-Z_]+' array-dimension ?
tag-definition = variable whitespace ':' whitespace array-dimmed-type (whitespace tag-enclosure) ? whitespace assign-op whitespace data-number ending-op
tag-definitions = (tag-definition <newline> <whitespace>) +
data-rhs-of-assign = '[' data-number (newline whitespace) ? (',' data-number (newline whitespace) ? ) * ']'
integer = '-' ? #'[0-9]+'
float = #'[-+]?[0-9]*\.[0-9]+'
engineering-float = float ('e+' | 'e-') integer
base-two-number = "2#" integer
single-quote-number = ("\'" | "\'=") ('$' (integer | 'r' | '1E' | '00<' | '1C' | '8D' | '8E')) + "\'"
data-number = base-two-number | integer | engineering-float | single-quote-number | data-rhs-of-assign
tag = "TAG" <newline whitespace> tag-definitions "END_TAG"

