<S> = task
ending-op = ';'
assign-op = ':='
<whitespace> = <#'\s+'>
word = #'[.\\0-9a-zA-Z_-]+'
newline = <'\r' ? '\n'>
integer = '-' ? #'[0-9]+'
base-number = integer '#' word
float = #'[-+]?[0-9]*\.[0-9]+'
version = "V" float
quote = '\"'
anything-word = #'[!?%<>(),$=\:.\\0-9a-zA-Z_-]+'
one-or-more-anythings = (anything-word whitespace) * anything-word ? whitespace ?
anything-string = quote one-or-more-anythings quote
rhs-of-assign = integer | float | version | base-number | "No" | "CONTINUOUS" | "PERIODIC"
array-dimension = <'['> integer <']'>
variable = #'[0-9a-zA-Z_]+' array-dimension ?
any-assign = variable <whitespace> assign-op <whitespace> rhs-of-assign
any-assign-comma = any-assign ',' newline whitespace
any-assigns = any-assign-comma * any-assign
enclosure = '(' any-assigns ')'
<task> = <"TASK"> whitespace word whitespace enclosure newline whitespace (variable ending-op newline whitespace) + <"END_TASK">
